spring:
  application:
    name: sisnacli
  config:
    import: "optional:classpath:xlstosql/${converter.active-profile}-mapping.yml"
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    driver-class-name: oracle.jdbc.OracleDriver

converter:
  # Valore placeholder che deve essere sovrascritto a runtime
  active-profile: "placeholder"