DROP TABLE IF EXISTS SOURCE_TABLE;
DROP TABLE IF EXISTS DEST_TABLE;

CREATE TABLE SOURCE_TABLE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE DEST_TABLE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    JOB_ID INT
);